name: CheckStyle Test workflow

on: 
  push:
  pull_request:

jobs:
  checkstyle_job:
    runs-on: ubuntu-latest
    name: Checkstyle job
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Run check style
    - uses: sane-fmt/action@master
